#!/bin/bash

ARGV="$@"

OPENRESTY="/usr/local/openresty/bin/openresty"
APP_HOME=`pwd`

ERROR=0

case $ARGV in
    start)
        $OPENRESTY -p $APP_HOME/
        ERROR=$?
        ;;
    stop|reload)
        $OPENRESTY -p $APP_HOME/ -s $ARGV
        ERROR=$?
        ;;
    *)
        echo 'usage: ./ngxctl start|stop|reload'
esac

if [ $ARGV == stop ]
then
	rm -rf $APP_HOME/html/images/*
fi

exit $ERROR

