#!/bin/bash

ARGV="$@"

OPENRESTY="openresty"
APP_HOME=`pwd`

ERROR=0

case $ARGV in
    start)
        $OPENRESTY -p $APP_HOME/ -c $APP_HOME/conf/nginx.conf
        ERROR=$?
        ;;
    stop|reload)
        $OPENRESTY -p $APP_HOME/ -c $APP_HOME/conf/nginx.conf -s $ARGV
        ERROR=$?
	rm -rf $APP_HOME/html/images/*
        ;;
    *)
        echo 'usage: ./ngxctl start|stop|reload'
esac

exit $ERROR

